IMAGENET_DIR = r"D:\projects\shape_dataset\imagenet_val"
IMAGENET_16CAT_DIR = r"D:\projects\shape_dataset\imagenet_16categories"
CHECKERBOARD_PREP = r"D:\projects\shape_dataset\checkerboard_prep_new"
CHECKERBOARD_DATASET_HUMAN = r"D:\projects\shape_dataset\xingye_stimuli\checkerboard_dataset_human"
CHECKERBOARD_GRAY_DATASET_HUMAN = r"D:\projects\shape_dataset\xingye_stimuli\checkerboard_gray_dataset_human"
INTACT_DATASET_HUMAN = r"D:\projects\shape_dataset\xingye_stimuli\intact_dataset_human"
JUMBLED_DATASET_HUMAN = r"D:\projects\shape_dataset\xingye_stimuli\jumbled_dataset_human"
