IMAGENET_DIR = r"D:\projects\shape_dataset\imagenet_val"
IMAGENET_16CAT_DIR = r"D:\projects\shape_dataset\imagenet_16categories"
CHECKERBOARD_PREP = r"D:\projects\shape_dataset\checkerboard_prep_new"
CHECKERBOARD_DATASET_HUMAN = r"D:\projects\shape_dataset\checkerboard_dataset_human_new"
CHECKERBOARD_GRAY_DATASET_HUMAN = r"D:\projects\shape_dataset\checkerboard_gray_dataset_human_new"
INTACT_DATASET_HUMAN = r"D:\projects\shape_dataset\intact_dataset_human_new"
JUMBLED_DATASET_HUMAN = r"D:\projects\shape_dataset\jumbled_dataset_human_new"
